# Generated by Django 3.2.1 on 2021-06-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_has_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_size',
        ),
    ]
