# Generated by Django 3.2.1 on 2021-06-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_product_has_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], max_length=1, null=True),
        ),
    ]
