# Generated by Django 3.2.1 on 2021-06-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
