# Generated by Django 3.2.1 on 2021-06-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='rider',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
